// Turn a delivered external master into the committed 64x96 grid the game
// loads, and print the conformance report while doing it.
//
//   npx tsx tools/ingest-master.ts conduit
//
// The delivered art lives in `art-src/` and is not shipped; this writes
// `src/art/masters/<id>.ts`, which is. Regenerate it deliberately — the file
// says so at the top — and read the report it prints before committing, because
// the pipeline reports and never repairs (ART_DIRECTION C.8.2).

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fitMasterToCanvas, formatReport, quantizeToPalette } from "../src/art/ingest.js";
import { SPRITE_HEIGHT, SPRITE_WIDTH } from "../src/art/sprites.js";
import { decodePNG } from "../src/art/png.js";
import type { JobId } from "../src/art/jobs.js";

interface Delivery {
  readonly jobId: JobId;
  readonly source: string;
  /** Which part of the delivered image holds the figure. */
  readonly crop: { x: number; y: number; w: number; h: number };
  readonly note: string;
}

const DELIVERIES: Readonly<Record<string, Delivery>> = {
  conduit: {
    jobId: "conduit",
    source: "art-src/vale/vale_sprite.png",
    // The delivery is one figure rendered twice, large on the right and small
    // on the left, rather than the front/back pair the brief asked for. The
    // large render is the one with detail to spend.
    crop: { x: 320, y: 0, w: 704, h: 1536 },
    note: "Vale, the Conduit. Front three-quarter only; the back view was not delivered.",
  },
};

const root = resolve(import.meta.dirname, "..");
const id = process.argv[2] ?? "";
const delivery = DELIVERIES[id];
if (!delivery) {
  throw new Error(`no delivery named "${id}"; known: ${Object.keys(DELIVERIES).join(", ")}`);
}

const image = decodePNG(readFileSync(resolve(root, delivery.source)));
const fitted = fitMasterToCanvas(image, { crop: delivery.crop });
const { grid, report } = quantizeToPalette(fitted);
console.log(formatReport(report, `${id}/se`));

const rows: string[] = [];
for (let y = 0; y < SPRITE_HEIGHT; y += 1) {
  let first = -1;
  let last = -1;
  for (let x = 0; x < SPRITE_WIDTH; x += 1) {
    if (grid.data[y * SPRITE_WIDTH + x]) {
      if (first < 0) first = x;
      last = x;
    }
  }
  rows.push(first < 0 ? `${y}: -` : `${y}: ${first}..${last} (${last - first + 1})`);
}
console.log("\nrow spans, for measuring the shoulder and hip lines:");
console.log(rows.join("\n"));

const base64 = Buffer.from(grid.data).toString("base64");
const out = resolve(root, `src/art/masters/${id}.ts`);
mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  `// Generated by \`npx tsx tools/ingest-master.ts ${id}\`. Do not edit by hand.
//
// ${delivery.note}
// Source: ${delivery.source}, crop ${JSON.stringify(delivery.crop)}.
// Intake report at generation time: ${report.ok ? "CONFORMS" : "REJECTED"} —
${report.errors.map((e) => `//   ERROR ${e}`).join("\n") || "//   (no errors)"}
${report.warnings.map((w) => `//   warn  ${w}`).join("\n")}
// See docs/ART_DIRECTION.md C.8.6 for what those mean and why the master ships
// anyway. How it is animated — landmarks, prop regions — lives in external.ts,
// because those are decisions, not delivered data.

/** Base64 of the ${SPRITE_WIDTH}x${SPRITE_HEIGHT} palette-index grid, row-major. */
export const GRID_BASE64 =
  ${JSON.stringify(base64)};
`,
);
console.log(`\nwrote ${out} (${base64.length} base64 chars)`);
